apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-App-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-App-1
  template:
    metadata:
      labels:
        app: my-App-1
    spec:
      containers:
      - name: my-App-1
        image: kubesamm/my-App-1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-App-1
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30001
  selector:
    app: my-App-1
